### PR TITLE
Add weekly view

### PR DESCRIPTION
**Pull request by vishandi**

### CODE REVIEW

**Comment by vishandi** [comment]
current UI:
image

**Comment by vishandi** [comment]
Current UI:
image

**Comment by tyanhan** [comment]
> current UI: image

I think it would be nicer if there was more spacing between days of week, and also a much larger gap between Upcoming and the full schedule.  Also I think we can rename the Bernice Yu's Schedule part to Bernice Yu's Full Schedule. Besides that I think the UI looks really great!

**Comment by tyanhan** [comment]
By the way, do you all think it would be nicer to list the time first, then the event itself? This way the timings will be aligned, so it is easier for the user to view.

**Comment by vishandi** [comment]
Current UI:
image

**Pull request merged**
